name: Automatic Build

on:
  workflow_dispatch: {}
  schedule:
  - cron: '*/10 * * * *'

jobs:
  build:
    name: Automatic Build
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}

    steps:
    - name: Checking out Repository
      uses: actions/checkout@master

    - name: Setting up Java
      uses: actions/setup-java@v3.4.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setting up node.js
      uses: actions/setup-node@v3.4.0
      with:
        node-version: '16.13.0'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v3.0.4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Installing dependencies
      run: yarn

    - name: Setup environment
      run: sh src/guizhan-build-setup.sh

    - name: Run automatic build
      id: guizhan-build
      run: node src/guizhan-build.js

    - name: Trigger nuxt build
      if: steps.guizhan-build.outputs.HAS_UPDATE == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.BOT_TOKEN }}
        event-type: nuxt-build
