name: Automatic Maven Build

on:
  workflow_dispatch: {}
  schedule:
  - cron: '*/10 * * * *'

jobs:
  build:
    name: Automatic Maven Build
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

    steps:
    - name: Checking out Repository
      uses: actions/checkout@master

    - name: Setting up Java
      uses: actions/setup-java@v2.4.0
      with:
        distribution: 'adopt'
        java-version: '16'
        java-package: jdk
        architecture: x64

    - name: Setting up node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16.13.0'

    - name: Installing dependencies
      run: yarn

    - name: Setup environment
      run: sh src/maven-build-setup.sh

    - name: Run automatic build
      id: maven-build
      run: node src/maven-build.js

    - name: Trigger nuxt build
      if: steps.maven-build.outputs.HAS_UPDATE == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: after-auto-build
